spring.application.name=sportcontrol

spring.datasource.url=jdbc:postgresql://localhost:5432/sport_db
spring.datasource.username=sport_user
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.devtools.restart.enabled=false