spring.application.name=sportcontrol

spring.datasource.url=jdbc:postgresql://localhost:5432/sport_db
spring.datasource.username=sport_user
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.devtools.restart.enabled=false

logging.level.org.hibernate.cache=DEBUG
logging.level.org.hibernate.engine.internal.StatisticalLoggingSessionEventListener=DEBUG
spring.jpa.properties.hibernate.generate_statistics=true

spring.jpa.properties.hibernate.cache.use_second_level_cache=true
spring.jpa.properties.hibernate.cache.region.factory_class=org.hibernate.cache.jcache.JCacheRegionFactory
spring.jpa.properties.javax.cache.provider=org.ehcache.jsr107.EhcacheCachingProvider
logging.level.com.example.sportcontrol.config=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.SQL=DEBUG

app.async.match-demo-delay-ms=30000
app.async.match.core-pool-size=16
app.async.match.max-pool-size=64
app.async.match.queue-capacity=1000
